config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  get 'home/about' => 'homes#about'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:index,:show, :edit, :update]
  resources :books, only: [:index, :create, :edit, :show, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

   has_one_attached :profile_image
   #titleがあるかのバリデーション
   validates :title, presence: true
   #ボディがあるかのバリデーション
   validates :body, length: { in: 1..200 }


def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
end

def favorited_by?(user)
  favorites.exists?(user_id: user.id)
end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


   has_one_attached :profile_image
   validates :name, presence: true, uniqueness: { case_sensitive: false }
   validates :name, length: { in: 2..20 }
   #ボディがあるかのバリデーション
   validates :introduction, length: { maximum: 50 }


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    if @comment.save
      @comment_new = BookComment.new
    end
    # redirect_to book_path(book)
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find(params[:id]).destroy
    # redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :is_matching_login_user, only: [:edit, :update]
  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
    @users = User.all
  end

  #def new
    #@book = Book.new #空のインスタンスを生成
  #end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      render :index
    end
  end


  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @books = Book.all
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    book =  Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

private

def book_params
  params.require(:book).permit(:title, :body)
end

def is_matching_login_user
  book = Book.find(params[:id])
  unless book.id == current_user.id
    redirect_to books_path
  end
end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # redirect_to book_path(book)
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_to book_path(book)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

  def create #共通ヘッダー制作中（（非ログイン時のサインインへのリンクが作りたい
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :is_matching_login_user, only: [:edit, :update]
  def index
  @books = Book.all
  @book = Book.new
  @user = current_user
  @users = User.all
  end

  def show
    #@user = User.find_by(id: params[:id])
    @user = User.find(params[:id])
    @book = Book.new
    @Users = User.all
    @books = @user.books
  end


  def edit
    # @user = current_user
    @user = User.find(params[:id])
    # if @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end



private

def user_params
  params.require(:user).permit(:name, :profile_image, :introduction)
end

def is_matching_login_user
  user = User.find(params[:id])
  unless user.id == current_user.id
    redirect_to user_path(current_user.id)
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/fovorites_helper.rb
module FovoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_book_comments.html.erb
<% book.book_comments.each do |book_comment| %>
  <p>
    <%= link_to user_path(book_comment.user.id) do %>
    <%= image_tag book_comment.user.get_profile_image(100,100) %>
      <%= book_comment.user.name %>
    <% end %>
      <%= book_comment.created_at.strftime('%Y/%m/%d') %>
      <%= book_comment.comment %>
      <% if book_comment.user == current_user %>
      <%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote:true, data: {"turbolinks" => false} %>
      <% end %>
<% end %>
</p>

app/views/book_comments/_form.html.erb
<%= form_with model: [book, book_comment], local: false do |f| %>
  <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
<% end %>

app/views/book_comments/create.js.erb
$('#book_comments').html("<%= j(render "book_comments/book_comments", book: @book) %>");
$('#comment_form').html("<%= j(render "book_comments/form", book: @book, book_comment:@comment_new) %>");
$('#comment_count').html("<%= @book.book_comments.count %>")
$("textarea").val('');

app/views/book_comments/destroy.js.erb
$('#book_comments').html("<%= j(render "book_comments/book_comments", book: @book) %>");
$('#comment_count').html("<%= @book.book_comments.count %>")

app/views/books/_books.html.erb
  <h1>User info</h1>
  <%= image_tag user.get_profile_image(100,100) %>
  <table class="table">
    <tbody>
      <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>

    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    </tbody>
  </table>

  <div class="row">
  <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
<!-- edit_user_path(user)に飛ばしたい（プロフ編集） -->
  <% end %>
</div>


<h1 class="mt-3">New book</h1>
<%= form_with model: book do |f| %>
  <div class="form-group">
    <h4>Title</h4>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <h4>Option</h4>
    <%= f.text_area :body %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class:'btn btn-success' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg5 px-5 px-sm-0 mx-auto">
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<h1>Editing Book</h1>
<%= form_with model: @book do |f| %>
  <div class="form-group">
  <h4>title</h4>
  <%= f.text_field :title, class:'form-control book_title' %>
  </div>
  <div class="form-group">
  <h4>opinion</h4>
  <%= f.text_area :body, class:'form-control book_body'%>
  </div>
  <div class="form-group">
    <%= f.submit "Update Book", class:'btn btn-secondary' %>
  </div>
  <% end %>


<%= link_to "Show" ,book_path(@book.id) %>
|
<%= link_to "Back" ,books_path %>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
      <!-- 部分テンプレート -->
      <%= render 'books', user: @user ,book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <!--<table class="table table-striped">-->

      <h1>Books</h1>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>
            </th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to user_path(book.user) do %>
              <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td id="favorite_buttons_<%= book.id %>">
              <!--部分テンプレート-->
              <%= render "favorites/favorites", book: book %>
              </td>
              <td><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
      <!-- 部分テンプレート -->
      <%= render 'books', user: @user, book: @book_new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <!--<table class="table table-striped">-->

      <h1>Book detail</h1>
      <table class="table table-hover table-inverse">
        <tbody>
            <tr>
              <td>
                <%= link_to user_path(@user.id) do %>
                <%= image_tag @user.get_profile_image(100,100) %><br>
                <%= @user.name %>
                <% end %>
              </td>
              <td><%= link_to @book.title, book_path(@book.id) %></td>
              <td><%= @book.body %></td>
              <td><% if @book.user == current_user %>
                <%= link_to"Edit", edit_book_path(@book), class: "btn btn-success" %>
                <% end %>
              </td>
              <td><% if @book.user == current_user %>
                <%= link_to"Destroy", book_path(@book), method: :delete , class: "btn btn-danger" %>
                <% end %>
              </td>
              <td>
                <% if @book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(@book), method: :delete do %>
                      ♥<%= @book.favorites.count %> いいね
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to book_favorites_path(@book), method: :post do %>
                      ♡<%= @book.favorites.count %> いいね
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td>
                <div>コメント件数：<span id="comment_count"><%= @book.book_comments.count %></span></div>
               <!--部分テンプレート（_book_comments.html.erb）-->
              </td>
              <!--<td>-->
                <!--部分テンプレート（_form.html.erb）-->
              <!--</td>-->
            </tr>
        </tbody>
      </table>
      <div id="book_comments">
        <%= render "book_comments/book_comments", book: @book %>
      </div>

      <div id="comment_form">
        <%= render "book_comments/form", book: @book, book_comment:@book_comment %>
      </div>
    </div>
  </div>
</div>

<!--もしログインユーザーの本投稿であればedit,destroyボタン-->

app/views/favorites/_favorites.html.erb
  <% if user_signed_in? %>
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
      ♥<%= book.favorites.count %>いいね
    <% end %>
    <% else %>
      <%= link_to book_favorites_path(book), method: :post, remote: true do %>
      ♡<%= book.favorites.count %>いいね
      <% end %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorites", book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorites", book: @book) %>");

app/views/homes/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>!</h1>
  </div>
</div>
</body>
</html>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In <i class="fa-solid fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in', user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in", method: :POST %>
        </div>
        <div class="row">
          <%= link_to 'Sign up', new_user_session_path, class:"btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <script src="https://kit.fontawesome.com/2699f28b7c.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <div class="social"></div>
  </head>
  <body>

      <header>
    <!-- <a href="https://a6bcb09b6861429db3394026482e57c4.vfs.cloud9.ap-northeast-1.amazonaws.com/">Bookers</a -->

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user.id), class:"nav-link text-light" do %>
              <i class="fa-solid fa-home"></i>Home
              <% end %>
            </li>

            <li class="nav-item">
              <a class="nav-link text-light" rel="nofollow"  href="/users">
              <i class="fa-solid fa-users"></i>Users</a>
            </li>

            <li class="nav-item">
              <a class="nav-link text-light" rel="nofollow"  href="/books">
              <i class="fa-solid fa-book-open"></i>Books</a>
            </li>

            <li class="nav-item">
              <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">
              <i class="fa-solid fa-sign-out-alt"></i>Log out</a>
            </li>


            <% else %>
            <li class="nav-item">
              <a class="nav-link text-light" href="/">
              <i class="fa-solid fa-home"></i>Home</a>
            </li>

            <li class="nav-item">
              <a class="nav-link text-light" rel="nofollow" href="/home/about">
              <i class="fa-solid fa-link"></i>About</a>
            </li>

            <li class="nav-item">
              <a class="nav-link text-light" rel="nofollow" href="/users/sign_up">
              <i class="fa-solid fa-user-plus"></i>Sign up</a>
            </li>

            <li class="nav-item">
              <a class="nav-link text-light" rel="nofollow" href="/users/sign_in">
              <i class="fa-solid fa-sign-in-alt"></i>Log in</a>
            </li>

            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

<main>
  <%= flash[:notice] %>
    <%= yield %>
</main>


<footer class="footer">
  <div class="container">
<p class="text-center">CopyRightInfratop.inc</p>
  </div>
</footer>

</body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg5 px-5 px-sm-0 mx-auto">
      <% if @user.errors.any? %>
        <%= @user.errors.count %>error prohibited this obj from being saved:
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
      <% end %>

    <h2>User Info</h2>
    <%= form_with model: @user do |f| %>
    <div class="form-group">
      <label for="inputName">Name</label>
      <%= f.text_field :name, autofocus: true, id:"inputName", class:'form-control name'%>
    </div>
    <div class="form-group">
      <label for="inputImage">Image</label>
      <%= f.file_field :profile_image, placeholder: "プロフィール画像", class: 'form-control-file user_image', accept: "image/*" %>
    </div>
    <div class="form-group">
      <label for="inputIntroduction">Introduction</label>
      <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction",class:"form-control introduction" %>
    </div>
    <div class="form-group">
    <%= f.submit "Update User", class:'btn btn-secondary' %>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">

      <!-- 部分テンプレート -->
      <%= render 'books/books', user: @user, book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <!--<table class="table table-striped">-->

      <h1>Users</h1>
      <table class="table table-hover table-inverse">
        <tbody>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(100,100) %></td>
                <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">

      <!-- 部分テンプレート -->
      <%= render 'books/books', user: @user, book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <!--<table class="table table-striped">-->

      <h1>Books</h1>
      <table class="table table-hover table-inverse">
        <tbody>
          <thead>
            <tr>
              <th></th>
              <th>title</th>
              <th>opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to user_path(book.user) do %>
                <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td><%= link_to "#{book.post_comments.count} コメント", book_path(book.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>